### ISSUE TITLE
example.cpp:17:71: error: ‘str_random_genotype’ was not declared in this scope

### ISSUE THREAD

**Issue by davidemms** [PabloCatalan/toylife#1]
Hi Pablo

I'm just trying to build your example but "str_random_genotype" in example.cpp is not declared/defined. The comment in the source code suggests it's in "helper_functions.cpp", but it appears to be missing.

Thanks
David

**Comment by PabloCatalan** [comment]
Hi David,

Thanks for being interested in toyLIFE! :)

Yes, you are right, the function is "random_genotype". I've already changed it in the source code, so it should be ok.

Sorry for the mess
Pablo

**Comment by davidemms** [comment]
Thanks great, thanks. I'm looking forward to trying it out!
